### PR TITLE
Enhanced refresh support

### PR DESCRIPTION
**Pull request by msokolov**
A few fixes I needed; I made refresh with no generation send the most recent batch of updates only, and I made it so having an incorrect generation in a request doesn't terminate the server. I also ran into a browser issue when testing with Glkote; firefox on mac was sending non-integral window sizes, I think

### CODE REVIEW

**Comment by erkyrath** [comment]
I will have to think about this. I don't like the idea of making the generation field optional. I *definitely* don't want generation number mismatch to be a tolerated error.

The use cases I imagine for the "refresh" message are:

- The client has crashed, and a new client is trying to connect to the game. (Or any other total-loss-of-state scenario.) The client sends "refresh" with generation 0. The library sends back the whole display history (perhaps cut off at some point in the past, but far enough back that the user doesn't care).
- The client has disconnected but still has its display state cached. It reconnects and sends "refresh" with its current generation. If that's up to date, the library sends back an empty update (or maybe status-window-only). If the client is not up to date, the library sends back just the part of the history that the client missed.

The second scenario isn't supported in my code because the library doesn't pay attention to the generation number. But that's the functionality I'm aiming at.

(You're in hackathon mode so you can hammer it however you want, of course.)

**Comment by erkyrath** [comment]
Unrelatedly, it is true that a browser can return a non-integral window size. (This typically happens after you've used cmd-plus/minus to change the display scale.) I will grab that change.

**Comment by msokolov** [comment]
So -- about handling gen mismatches. My approach here is not to "allow" them, in the sense that all we do is to return an error message, and significantly -- don't exit. This gives the client a chance to request a refresh. Basically the dialog is like this:
CLIENT: request with bad gen number
SERVER: ERROR (bad gen number)
CLIENT: refresh
SERVER: update, including latest gen number
CLIENT: pick up where we left off ...

**Comment by BroadcastGames** [comment]
"The scenario I encountered was that our client (which is really a kind of middle tier) got confused about its generation number. I think the hosting environment is buggy since we set the number in a session, but it doesn't seem to persist; the next request is made using an older gen number, but we have no way of detecting the failure other than relying on the remglk server to tell us."

I envision I'm going to need to be able to resync a lost GUI with the RemGlk side too. I'll look over this code.

Could forcing the game to save/restore, basically 1. save game, 2 restart remglk, 3. start sequence at beginning work?  On a GUI crash or loss, RemGlk treat it as a save?  even as an IFDEF directive in the code this would seem a useful feature.

**Comment by erkyrath** [comment]
The generation number functions as an ASSERT of consistency between the client and the server. It should never be necessary to ignore it. The original poster mentioned a buggy hosting environment; that's what would have to be addressed.

Closing this PR as incorrect.

**Pull request closed without merging**
